More types
ergoplatform/sigma-rust pull request #229
Opened 2021-04-08 11:01 UTC by Shimuuar

Implementation is copied from  `sigmastate/src/main/scala/sigmastate/types.scala`. Thus being product of copy-paste it's possible that I mixed up something.

P.S. What is good place to put `property` function? So far I just duplicated it

2021-04-08 12:21 UTC, greenhat requested changes
Thank you! Looking good. Please, check my comments.

2021-04-08 12:21 UTC, greenhat commented on ergotree-ir/src/types/sglobal.rs
> +/// SBox type id
```suggestion
/// SGlobal type id
```

2021-04-08 12:21 UTC, greenhat commented on ergotree-ir/src/types/sglobal.rs
> +/// Box.groupGenerator property
```suggestion
/// groupGenerator property
```

2021-04-08 12:21 UTC, greenhat commented on ergotree-ir/src/types/sglobal.rs
> +/// Box.xor property
```suggestion
/// "xor" predefined function
```

2021-04-08 12:21 UTC, greenhat commented on ergotree-ir/src/types/sglobal.rs
> +            t_range: SType::SGroupElement.into(),
```suggestion
            t_range: SType::SColl(SType::SByte.into()).into(),
```

2021-04-08 12:21 UTC, greenhat commented on ergotree-ir/src/types/sheader.rs
> +fn property(name: &'static str, tpe: SType, id: MethodId) -> SMethodDesc {
It looks like `SMethodDesc` constructor to me. How about moving it into `SMethodDesc::property(...)`?

2021-04-08 12:21 UTC, greenhat commented on ergotree-ir/src/types/stype.rs
> +    /// Header o block without solved mining puzzle
```suggestion
    /// Header of a block without solved mining puzzle
```

2021-04-08 12:21 UTC, greenhat commented on ergotree-ir/src/types/stype.rs
> +    SGlobal,
Please, add new `SType` variants to the `Arbitrary` impl. It'll cover type serialization code.

2021-04-08 13:36 UTC, Shimuuar commented
I addressed review comments. 

I also took a second look at `property` function. Now I'm not sure whether it's correct. Should `t_dom` be empty vector or should it be singleton vector? Also current implementation of `PropertyCall` (https://github.com/ergoplatform/sigma-rust/blob/4c269ab6338600955fc1c482404fe74a913ad06c/ergotree-ir/src/mir/property_call.rs#L20-L25) requires that `t_dom` is singleton vector. Is that implementation incomplete?

2021-04-08 15:56 UTC, greenhat commented
> I addressed review comments.
> 
> I also took a second look at `property` function. Now I'm not sure whether it's correct. Should `t_dom` be empty vector or should it be singleton vector? Also current implementation of `PropertyCall` (
> 
> https://github.com/ergoplatform/sigma-rust/blob/4c269ab6338600955fc1c482404fe74a913ad06c/ergotree-ir/src/mir/property_call.rs#L20-L25
> 
> ) requires that `t_dom` is singleton vector. Is that implementation incomplete?

Oh, I missed that. `t_dom` should be a singleton vector with an object type of the property (`SGlobal` in case of global/predefined functions). One more parameter to the `property` constructor. Or even better, how about adding `tpe: SType` field to `STypeCompanionHead` and adding `property_tpe` method so that we have a call like `S_BOX_COMPANION_HEAD.property_tpe(...)`?

2021-04-09 09:05 UTC, Shimuuar commented
> t_dom should be a singleton vector

That couldn't be right. `xor` should take 2 byte arrays as input as well. Indexing of collections already takes two parameters: 
https://github.com/ergoplatform/sigma-rust/blob/4c269ab6338600955fc1c482404fe74a913ad06c/ergotree-ir/src/types/scoll.rs#L37-L45

Looks like correct invariant is `t_dom` should have at least 1 parameter and first parameter is type of object.

2021-04-09 09:07 UTC, Shimuuar commented
P.S. Should `SFunc` of collection indexing mention type variables?

2021-04-09 09:31 UTC, Shimuuar commented
> Or even better, how about adding tpe: SType field to STypeCompanionHead

What should it be equal to for collections? Two defined methods use different type variables

2021-04-09 09:37 UTC, greenhat commented
> > t_dom should be a singleton vector
> 
> That couldn't be right. `xor` should take 2 byte arrays as input as well. Indexing of collections already takes two parameters:
> https://github.com/ergoplatform/sigma-rust/blob/4c269ab6338600955fc1c482404fe74a913ad06c/ergotree-ir/src/types/scoll.rs#L37-L45
> 
> Looks like correct invariant is `t_dom` should have at least 1 parameter and first parameter is type of object.

Yes, you're right. I should've clarified that singleton vector is only for object properties. For method, it's object's type followed be argument types. `SGlobal` is an exception, only function argument types are in `t_dom`.

2021-04-09 09:44 UTC, greenhat commented
> P.S. Should `SFunc` of collection indexing mention type variables?

Yes.

2021-04-09 09:51 UTC, greenhat commented
> > Or even better, how about adding tpe: SType field to STypeCompanionHead
> 
> What should it be equal to for collections? Two defined methods use different type variables

`SColl(STypeVar.iv())` should fit ("iv" means "Input Value"). We have this convention in Scala version. And all `Coll` methods use the same type variable (`STypeVar.iv()`) for collection element type in their sigs.

2021-04-09 17:26 UTC, Shimuuar commented
I went for variant with extra parameter in property function. Mostly to avoid dealing with question which type should contain `STypeCompanionHead` for collections and why it's different from first parameter of method (different type variables).

2021-04-13 06:02 UTC, greenhat approved these changes
Thanks! Sorry for the delay, I did not get from your last comment that this PR was ready for review.

2021-04-13 06:02 UTC, merged