Implement GetVar
ergoplatform/sigma-rust pull request #236
Opened 2021-04-19 09:57 UTC by Shimuuar

This is partial implementation of GetVar. Serialization is implemented but there's  only skeleton for evaluator.

 1. What types are allowed in GetVar? For now tests just hardcode `SInt`.
 2. Evaluation should apparently extract some variables from context. But what are those variables? Are they not present in context yet?

PR also contains fix to SigmaToBoolean type

2021-04-19 12:03 UTC, greenhat commented
> 1. What types are allowed in GetVar? For now tests just hardcode `SInt`.

Any type data type, really (any `Constant` to be precise).  

> 2. Evaluation should apparently extract some variables from context. But what are those variables? Are they not present in context yet?
Yes, there is `ContextExtension` that holds the variables. Could you add it to `Context`, please. Here is an eval for `getVar` - 
https://github.com/ScorexFoundation/sigmastate-interpreter/blob/6c51c13f7a494a191a7ea5645e56b04fb46a418d/sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala#L749-L783
Be aware, the variables at the end are stored in an array with gaps for missing ids. See - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/6c51c13f7a494a191a7ea5645e56b04fb46a418d/sigmastate/src/main/scala/org/ergoplatform/ErgoLikeContext.scala#L133-L140
I'm quite sure it was done for performance reasons only. We can skip it and keep using hash map for storage.

2021-04-20 09:33 UTC, Shimuuar commented
I added simplest possible set of variables. Should it be `HashMap<u8,Constant>` or `HashMap<u8,Value>`? I picked former since it looks there's no way to compute type of `Value`

Set of variables in context is always initialized to empty map. Is this right choice for `ergo_lib::wallet::signing::make_context`? What is good choice for `Arbitrary` instance for `Context`?

2021-04-21 05:30 UTC, greenhat requested changes
Thanks! Looking good!

> I added simplest possible set of variables. Should it be `HashMap<u8,Constant>` or `HashMap<u8,Value>`? I picked former since it looks there's no way to compute type of `Value`.

Good choice! But `ContextExtension` is even better (see my comment).
 
> Set of variables in context is always initialized to empty map. Is this right choice for `ergo_lib::wallet::signing::make_context`? 

In the future, it should be passed to `make_context` as a parameter. Let's use empty for now (`ContextExtension::empty()`).

> What is good choice for `Arbitrary` instance for `Context`?

`ContextExtension` has `Arbitrary` implementation. Let's pass that.

2021-04-21 05:30 UTC, greenhat commented on ergotree-interpreter/src/eval/context.rs
> +    pub var_map: HashMap<u8, Constant>,
Could you make it  `extension: ContextExtension,` instead, please? We're going to need to manipulate multiple `ContextExtension` in the future, and to keep it consistent with Scala version (see `ErgoLikeContext`, our `Context` sister type there).

2021-04-21 05:30 UTC, greenhat commented on ergotree-interpreter/src/eval/get_var.rs
> +                "expected {:?}, found {:?}",
```suggestion
                "GetVar: expected {:?}, found {:?}",
```

2021-04-21 05:30 UTC, greenhat commented on ergotree-interpreter/src/eval/get_var.rs
> +}
Although the eval code is fairly simple it'd be nice to have tests covering all three cases, just to catch a regression.

2021-04-21 08:34 UTC, Shimuuar commented
I've addressed eveything

2021-04-21 09:56 UTC, greenhat approved these changes

2021-04-21 09:56 UTC, greenhat commented on ergotree-interpreter/src/eval/context.rs
> +    ///
```suggestion
    /// prover-defined key-value pairs, that may be used inside a script
```

2021-04-21 10:02 UTC, greenhat commented
> I've addressed eveything

Thank you!

2021-04-21 11:09 UTC, merged