358 coll updated
ergoplatform/sigma-rust pull request #364
Opened 2021-08-09 01:19 UTC by ApexTheory

PR for https://github.com/ergoplatform/sigma-rust/issues/358

FYI this branch is based off the [Coll.indices PR branch](https://github.com/ergoplatform/sigma-rust/pull/363) to avoid any merge conflicts.

2021-08-09 09:24 UTC, greenhat requested changes
Looking great! 
Could you implement my comments from #363 here? So we can drop #363 and merge only this one. Next time you can just create one PR. There is no strict rule 1 PR = 1 issue. :)

2021-08-09 09:24 UTC, greenhat commented on ergotree-interpreter/src/eval/scoll.rs
> +    fn eval_update_oob() {
Nice!

2021-08-10 03:43 UTC, ApexTheory commented
@greenhat I incorporated your suggestions from Coll.indices here.  This PR has the solution for update & indices now.

2021-08-10 09:39 UTC, greenhat approved these changes
Looking great! Thank you!

2021-08-10 09:39 UTC, greenhat commented on ergotree-ir/src/types/scoll.rs
> +pub const ZIP_METHOD_ID: MethodId = MethodId(29);
Good catch! I appreciate it! Thank you!

2021-08-10 09:40 UTC, merged