`AvlTree.insert` operation
ergoplatform/sigma-rust pull request #413
Opened 2021-09-26 06:36 UTC by kettlebell

Close #411

2021-09-28 08:17 UTC, kettlebell commented on ergotree-interpreter/src/eval/savltree.rs
> +            |digest| Node::LabelOnly(NodeHeader::new(Some(*digest), None)),
The Rust AVL library has this notion of `Resolver` that's not present in the scala implementation. I just copied what was used in the library example.

2021-09-28 08:21 UTC, kettlebell commented on ergotree-interpreter/src/eval/savltree.rs
> +                None,
I'm not sure how this parameter is used for AVL operations. Setting it to None here and for `AvlTreeData::value_length_opt` allowed the test to pass.

2021-09-29 11:14 UTC, greenhat commented
`scorex_crypto_avltree` addition broke `ergo-lib-wasm` build by pulling new `rand`. Please update `rand` version in all our crates to `0.8.4`(or .3) and 
update `getrandom = {version = "0.1", features = ["wasm-bindgen"]}` in `ergo-lib-wasm` to `getrandom = {version = "0.2.3", features = ["js"]}`.
`

2021-09-29 12:06 UTC, greenhat requested changes
Great job figuring out AVL trees! Looking great! Check minor comments.

2021-09-29 16:02 UTC, greenhat commented
> > `scorex_crypto_avltree` addition broke `ergo-lib-wasm` build by pulling new `rand`. Please update `rand` version in all our crates to `0.8.4`(or .3) and update `getrandom = {version = "0.1", features = ["wasm-bindgen"]}` in `ergo-lib-wasm` to `getrandom = {version = "0.2.3", features = ["js"]}`. `
> 
> I've updated the dependencies in my latest commit, but CI is totally broken as you can see. Each test refers to errors in ergotree-ir/src/mir/constant.rs, but the code doesn't match the commit. Not sure what's going on.
> 
> Also please note that I had to update more than just `rand` and `getrandom`. Details in commit message.

Judging by compiler error I believe you need to rebase this branch onto fresh develop, after I merged SubstConstants PR. For some reason Github UI did not pick up new develop branch.

2021-09-30 06:33 UTC, kettlebell commented on ergotree-ir/src/mir/constant.rs
> +    AvlTree(AvlTreeData),
Done.

2021-09-30 06:33 UTC, kettlebell commented on ergotree-ir/src/mir/value.rs
> +    AvlTree(AvlTreeData),
Done.

2021-09-30 06:33 UTC, kettlebell commented on ergotree-ir/src/types/savltree.rs
> +        tpe: SFunc {
Thanks.

2021-09-30 06:35 UTC, kettlebell commented on ergotree-ir/src/mir/avl_tree_data.rs
> +        if let Some(l) = self.value_length_opt {
There's existing impl for `Option<Box<T>>` so I went with that (trying to implement it for `Option<T>` lead to compiler complaints).

2021-09-30 06:35 UTC, kettlebell commented on ergotree-ir/src/mir/avl_tree_data.rs
> +        let is_some = {
Done.

2021-09-30 06:35 UTC, kettlebell commented on ergotree-interpreter/src/eval/savltree.rs
> +    let mut avl_tree_data = match obj {
Done.

2021-09-30 06:36 UTC, kettlebell commented on ergotree-interpreter/src/eval/savltree.rs
> +        return Err(EvalError::Misc("AvlTree: Insertions not allowed".into()));
I went with `EvalError::AvlTree(String)`.

2021-09-30 06:36 UTC, kettlebell commented on ergotree-interpreter/src/eval/savltree.rs
> +        match v {
Thanks, saved a lot of lines. Need to remember to use this trait more!

2021-09-30 06:37 UTC, kettlebell commented on ergotree-ir/src/serialization/data.rs
> +            Literal::AvlTree(a) => a.sigma_serialize(w)?,
Done.

2021-09-30 06:38 UTC, kettlebell commented
> > > `scorex_crypto_avltree` addition broke `ergo-lib-wasm` build by pulling new `rand`. Please update `rand` version in all our crates to `0.8.4`(or .3) and update `getrandom = {version = "0.1", features = ["wasm-bindgen"]}` in `ergo-lib-wasm` to `getrandom = {version = "0.2.3", features = ["js"]}`. `
> > 
> > 
> > I've updated the dependencies in my latest commit, but CI is totally broken as you can see. Each test refers to errors in ergotree-ir/src/mir/constant.rs, but the code doesn't match the commit. Not sure what's going on.
> > Also please note that I had to update more than just `rand` and `getrandom`. Details in commit message.
> 
> Judging by compiler error I believe you need to rebase this branch onto fresh develop, after I merged SubstConstants PR. For some reason Github UI did not pick up new develop branch.

Done, plus addressed all your concerns (with one little exception for the unresolved conversation above).

2021-09-30 08:33 UTC, greenhat approved these changes
Looking great! Thank you!

2021-09-30 08:34 UTC, merged