Convert vendored dependencies of `ergo-rest` into sub-modules
ergoplatform/sigma-rust pull request #571
Opened 2022-04-30 15:41 UTC by kettlebell

Close #570

2022-05-01 07:19 UTC, kettlebell commented on .github/workflows/ci.yml
> -      - name: run `reqwest-wrap` WASM tests
I had these tests here originally to test the timeout PR that was applied on top of `reqwest`. After moving it under `ergo-rest`, the WASM tests for it no longer compiles, due to a really weird error in the dependency hierarchy (for reference it's exactly this error message: https://github.com/alexcrichton/wait-timeout/issues/25).

I've opted to delete it for now.

2022-05-01 07:20 UTC, kettlebell commented on ergo-rest/src/wasm_timer/timer/ext.rs
> -    ///
I deleted this doctest since otherwise we'd leak some `wasm-timer` internals through `ergo-rest`.

2022-05-02 05:21 UTC, greenhat requested changes
Looking great! I appreciate your description of submodules in the readme file. Thank you!
One minor request - to exclude vendored sub-modules from test coverage tracking. Could you please add them to the existing `--exclude-files` option in ci.yml?

2022-05-02 06:31 UTC, kettlebell commented
Made the change.

2022-05-02 07:22 UTC, greenhat approved these changes
Thank you!

2022-05-02 07:22 UTC, merged